### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tommyh** [keygen-sh/request_migrations#2]
Hi, I just saw this [from HN](https://news.ycombinator.com/item?id=31855521), but can't comment there because the thread is too old (23 days).

This gem looks very very cool.  When I saw that you were handling API versions, I expected a simple DSL around feature toggles for semantic API versions....  but this is a middleware for business logic transformations.

Some ideas for your docs:

1. The usage docs start great, but then I'm lost when I hit this line: `migrate if: -> data { data in type: 'user' } do |data|`.  You might want to provide a sample of what the input is.  A request object?  Vanilla hash from the controller?  response body?  Is the `'user'` some meta programming on the ActiveModel type?  After reading further, I think the controller is returning `render json: {type: 'user', first_name: 'Jane', last_name: 'Doe', ... }`,  but I'm not sure to be honest.

2. You might want to record a screencast going through all of this very slowly.  This gem has a lot to it, so a full lesson might be helpful to walk people through it slowly.

Just some thoughts!  :)

**Comment by ezekg** [comment]
Thanks for the feedback. You're correct that this is for applying transformations on business logic.

In the case of the `migrate` method, `data` is whatever you provide to `migrate!` within a request or response migration. It could be a hash (parsed JSON payload), an HTML string, an XML string, etc. — it's entirely dependent on input.

And the `data in type: 'user'` line is using [pattern matching](https://docs.ruby-lang.org/en/3.0/syntax/pattern_matching_rdoc.html) to match against the input `data`. The lambda will return true if `data` matches the pattern, i.e. it's a hash containing a key `type` with value `'user'`.

I'll spend some time and update the docs soon.
